print("NAMA : MUHAMAD AKBAR FADILAH")
print("NIM : 20200801269")
print("FAKULTAS : ILMU KOMPUTER")
print("JURUSAN : TEKNIK INFORMATIKA")
print("------------------------------")
print("Saya Belajar Bahasa Pemrograman Menggunakan Python")